
[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false
ansible_ssh_private_key_file=~/keys/terra-key-ansible



[control]
control-node-ubuntu ansible_connection=local ansible_user=ubuntu

[ubuntu_workers]
worker-ubuntu ansible_host=172.31.32.212 ansible_user=ubuntu

[redhat]
worker-redhat ansible_host=34.210.169.226 ansible_user=ec2-user

[amazon]
worker-amazon ansible_host=34.220.124.33 ansible_user=ec2-user
